services:
    PavelLysiankou\OpenApiGenerator\Service\RequestDtoFormTypeResolver:

    PavelLysiankou\OpenApiGenerator\ArgumentResolver\RequestDTOResolver:
        autowire: true
        autoconfigure: true
